import type { Metadata } from "next";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
        <head>
          <link rel="stylesheet" href="/assets/css/animate.min.css" />
          <link rel="stylesheet" href="/assets/css/bootstrap.min.css" />
          <link rel="stylesheet" href="/assets/css/nice-select.css" />
          <link rel="stylesheet" href="/assets/css/backToTop.css" />
          <link rel="stylesheet" href="/assets/css/owl.carousel.min.css" />
          <link rel="stylesheet" href="/assets/css/swiper.min.css" />
          <link rel="stylesheet" href="/assets/css/odometer-theme-default.css" />
          <link rel="stylesheet" href="/assets/css/magnific-popup.css" />
          <link rel="stylesheet" href="/assets/css/main.css" />
          <link rel="stylesheet" href="/assets/css/light-mode.css" />
          <link rel="stylesheet" href="/assets/css/responsive.css" />
          <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css" />
          <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css" />

          {/* <script src="/assets/js/jquery.min.js"></script> */}
          {/* <script src="/assets/js/bootstrap.bundle.min.js"></script>
          <script src="/assets/js/smooth-scroll.js"></script> */}
          {/* <script src="/assets/js/appear.min.js"></script> */}
          {/* <script src="/assets/js/wow.min.js"></script> */}
          {/* <script src="/assets/js/gsap.min.js"></script>
          <script src="/assets/js/one-page-nav.js"></script>
          <script src="/assets/js/lightcase.js"></script>
          <script src="/assets/js/owl.carousel.min.js"></script>
          <script src="/assets/js/swiper.min.js"></script>
          <script src="/assets/js/imagesloaded-pkgd.js"></script>
          <script src="/assets/js/isotope.pkgd.min.js"></script>
          <script src="/assets/js/odometer.min.js"></script>
          <script src="/assets/js/magnific-popup.js"></script>
          <script src="/assets/js/main.js"></script> */}
        </head>
        <body>
          {children}
        </body>
    </html>
  );
}
